baseURL = "https://www.cleeb.net"
languageCode = "en-us"
title = "Cleeb"
theme = "hugo-profile"
Paginate = 3
enableRobotsTXT = true

[outputs]
home = [ "HTML", "RSS", "JSON" ]
page = [ "HTML", "RSS" ]

[markup.goldmark.renderer]
unsafe = true

[[Menus.main]]
identifier = "blog"
name = "Blog"
title = "Blog posts"
url = "/blogs"
weight = 1

# [[Menus.main]]
# identifier = "gallery"
# name = "Gallery"
# title = "Blog posts"
# url = "/gallery"
# weight = 2

[params]
title = "Cleeb!"
description = "cleeb's homepage on the world wide web"
favicon = "/favicon.ico"
useBootstrapCDN = false
mathjax = false
animate = true

  [params.font]
  fontSize = "1rem"
  fontWeight = 400
  lineHeight = 1.5
  textAlign = "left"

  [params.navbar]
  align = "ms-auto"
  brandName = "Cleeb!"
  disableSearch = true
  enableSeparator = false

    [params.navbar.stickyNavBar]
    enable = true
    showOnScrollUp = true

    [params.navbar.menus]
    disableAbout = false
    disableExperience = false
    disableEducation = false
    disableProjects = false
    disableAchievements = false
    disableContact = false

  [params.hero]
  enable = true
  intro = "Howdy, I'm"
  title = "Cleeb"
  subtitle = "aka Caleb Smith"
  content = "devsecops practitioner, hacker, and radio nerd in the Seattle area"
  image = "/images/smol-cleeb-logo-2.png"

    [params.hero.bottomImage]
    enable = true

    [params.hero.button]
    enable = true
    name = "Resume"
    url = "#"
    download = true
    newPage = false

[[params.hero.socialLinks.fontAwesomeIcons]]
icon = "fab fa-github"
url = "https://github.com/cschmittiey"

[[params.hero.socialLinks.fontAwesomeIcons]]
icon = "fab fa-x-twitter"
url = "https://x.com/cleebian"

[[params.hero.socialLinks.fontAwesomeIcons]]
icon = "fa-regular fa-envelope"
url = "mailto:cleeb+website@cleeb.net"

  [params.about]
  enable = true
  title = "About Me"
  image = "/images/me.webp"
  content = """
I am a DevSecOps Engineer with an interest in building secure, reliable systems. I have a background in cybersecurity and computer engineering, and I have a strong interest in being at the intersection of radio and computers."""

    [params.about.skills]
    enable = true
    title = "Here are a few technologies I've been working with recently:"
    items = [ "Linux", "Kubernetes", "Terraform", "AWS", "Python", "Go", "Whisper", "Flux" ]

  [params.experience]
  enable = true

    [[params.experience.items]]
    job = "Development Security Systems Engineer"
    company = "Ingo Payments"
    companyUrl = "https://ingopayments.com"
    date = "May 2022 - Present"
    content = "Currently working on: securing and modernizing hybrid cloud infrastructure, PCI compliant IaaC, and CI/CD pipelines."

      [params.experience.items.featuredLink]
      enable = false  
      name = "View the project"
      url = "https://example.com"
      
      [params.experience.items.info]
      enable = false
      content = "This is a remote position."

    [[params.experience.items]]
    job = "Software Services Assistant"
    company = "Everlight Solar"
    companyUrl = "https://everlightsolar.com/"
    date = "Mar 2021 - Apr 2022"
    content = """
• Improved cybersecurity posture through SSO, automated onboarding and offboarding, CIS Controls

• Managed user accounts across Google Workspace, Slack, Gong, TalentLMS, Zoom, Zoom Phone

• Designed and installed a TrueNAS storage and 10g networking solution for video editing
"""

      [params.experience.items.featuredLink]
      enable = false
      url = "https://example.com"

      [params.experience.items.info]
      enable = false
      content = "I worked as a software developer for more than one year in Amazon."

    [[params.experience.items]]
    job = "Helpdesk Technician"
    company = "Autonomous Solutions Inc"
    companyUrl = "https://asirobots.com"
    date = "Nov 2020 - Mar 2021"
    content = """
• Worked with end-users to reach satisfactory resolutions to helpdesk tickets

• Developed scripts and internal tooling to automate deployment of laptops for new hires

• Troubleshooted wired and wireless network performance issues
"""

      [params.experience.items.featuredLink]
      enable = false
      url = "https://example.com"

      [params.experience.items.info]
      enable = true
      content = "Worked here for 5 months until Everlight offered me my old position back with double the pay"

    [[params.experience.items]]
    job = "XM Tech Support Specialist"
    company = "Everlight Solar"
    companyUrl = "https://everlightsolar.com/"
    date = "Aug 2019 - Aug 2020"
    content = """
• Created and maintained Qualtrics surveys for our customer base to measure satisfaction and engagement

• Acted as internal tech support for the company’s sales and recruitment teams

• Administered AWS cloud infrastructure and wrote Python scripts to handle data syncing when needed
"""

      [params.experience.items.featuredLink]
      enable = false
      url = "https://example.com"

      [params.experience.items.info]
      enable = false
      content = "This is a remote position."

  [params.education]
  enable = true
  index = false

    [[params.education.items]]
    title = "BS Cybersecurity and Information Assurance"
    date = "2021 - expected Sept 2024"
    # GPA = "3.8 out of 5.0"
    content = """
I originally began my bachelors in Computer Engineering at Utah State University, but halfway through my needs changed and I began working full-time. I am finishing up my degree at WGU in my evenings."""

      [params.education.items.school]
      name = "Western Governors University"
      url = "https://wgu.edu"

  [params.achievements]
  enable = false

    [[params.achievements.items]]
    title = "Google kickstart runner"
    content = "I solved all problems with optimal solution."
    url = "https://example.com"
    image = "/images/achievment.jpg"

    [[params.achievements.items]]
    title = "Facebook Hackathon Winner"
    content = "Developed a product using Artificial Intelligence."
    image = "/images/achievment.jpg"

    [[params.achievements.items]]
    title = "Hugo Profile"
    content = "Developed a theme and getting 1K+ downloads per month."
    url = "https://github.com/gurusabarish/hugo-profile"
    image = "/images/achievment.jpg"

    [[params.achievements.items]]
    title = "Microsoft Imagine Runner"
    content = "We are developed a product which can help others."

    [[params.achievements.items]]
    title = "Google Summer of Code"
    content = "Contributed to a open source project."
    url = "https://example.com"

  [params.projects]
  enable = true

    [[params.projects.items]]
    title = "GitOps Kubernetes Homelab"
    content = "I run my homelab using kubernetes with flux, longhorn, sops, etc."
    image = "/images/k8s-homelab.png"
    badges = [ "YAML", "Go", "Kubernetes" ]

      # [params.projects.items.featured]
      # name = "Demo"
      # link = "https://hugo-profile.netlify.app"

      # [[params.projects.items.links]]
      # icon = "fa fa-envelope"
      # url = "mailto:?subject=Hugo%20Profile%20Template&body=Check%20it%20out:%20https%3a%2f%2fhugo-profile.netlify.app%2fblog%2fmarkdown-syntax%2f"

      [[params.projects.items.links]]
      icon = "fab fa-github"
      url = "https://github.com/cschmittiey/k8s-homelab"

      # [[params.projects.items.links]]
      # icon = "fab fa-twitter"
      # url = "https://twitter.com/intent/tweet?text=Check+it+out:&url=https%3A%2F%2Fgithub.com%2Fgurusabarish%2Fhugo-profile"

    [[params.projects.items]]
    title = "AI Radio Transcription"
    content = "A simple python app to transcribe audio from trunked radio systems like PSERN using NVIDIA and OpenAI ASR models locally."
    image = "/images/100p.jpg"
    badges = [ "Python", "Whisper", "Canary" ]

      [params.projects.items.featured]
      name = "Demo"
      link = "https://discord.gg/DcGJX9hRwB"

      [[params.projects.items.links]]
      icon = "fab fa-github"
      url = "https://github.com/cschmittiey/simple-tr-transcription"

    [[params.projects.items]]
    title = "Open Ham Wiki"
    content = "An open respository for all things amateur radio, including guides, tutorials, and links to other resources."
    image = "/images/openham_logo.png"
    badges = [ "MediaWiki", "Docker Compose" ]

      [params.projects.items.featured]
      name = "Wiki"
      link = "https://openham.wiki/index.php/Main_Page"

      # [[params.projects.items.links]]
      # icon = "fab fa-github"
      # url = "https://github.com/gurusabarish/HugoProfileV2"

  [params.contact]
  enable = true
  content = "Whether you want to simply say hello or you have a project in mind, I'd love to hear from you."
  btnName = "send me electronic mail"
  btnLink = "mailto:cleeb+websitebutton@cleeb.net"

[params.footer.recentPosts]
path = "blogs"
count = 3
title = "Recent Posts"
enable = true
disableFeaturedImage = false

[params.footer.socialNetworks]
github = "https://github.com/cschmittiey"
linkedin = "https://linkedin.com/in/caleb-d-smith"
twitter = "https://twitter.com/cleebian"
# instagram = "https://instagram.com"
# facebook = "https://facebook.com"

  [params.listPages]
  disableFeaturedImage = false

  [params.singlePages]
  socialShare = true

    [params.singlePages.readTime]
    enable = true
    content = "min read"

    [params.singlePages.scrollprogress]
    enable = true

    [params.singlePages.tags]
    openInNewTab = true

  [params.terms]
  read = "Read"
  toc = "Table Of Contents"
  copyright = "cleeb, all rights reserved"
  pageNotFound = "Page not found"
  emailText = "Check out this site"

  [params.datesFormat]
  article = "Jan 2, 2006"
  articleList = "Jan 2, 2006"
  articleRecent = "Jan 2, 2006"

